### ISSUE TITLE
stop in payload is not stopping timer

### ISSUE THREAD

**Issue by Jai-Gogineni** [hamsando/node-red-contrib-stoptimer-varidelay#15]
Hi

```
msg.payload = {
        On :1,
        stop:1
        
    }
    msg.stop = true
return msg;

```

is not stopping timer it still executes am I missing anything ?

Thanks

**Comment by hamsando** [comment]
It only stops if msg.payload == "stop" 
You have other things in the payload, and the timer does not consider that as an instruction for itself.
