### ISSUE TITLE
More a suggestion - remaining time output.

### ISSUE THREAD

**Issue by Just-another-pleb** [hamsando/node-red-contrib-stoptimer-varidelay#17]
It may be nice for people to have a value output for time left rather than a human readable value.

So if it is 2 hours, 15 minutes 33 seconds:
It could be output as:  135 minutes or 8133 seconds.

Then if you wanted to extend the time you could get that value and add the time to extend (in minutes or seconds - in these cases) and send it back into the node with the new value.

**Comment by hamsando** [comment]
I've now got this implemented locally. Will do some testing during the weekend and release it probably Sunday.

**Comment by Just-another-pleb** [comment]
Quick thought.
Your third output (originally) outputs time in human readable format and you are *adding* an output that gives remaining time in seconds.

Is it *worth* keeping the human readable output?
I'm only saying that because there is now a `moment` node that may be able to convert the number of seconds remaining (or with a small cheat) to human readable.
The *cheat* if the `moment` wants milliseconds: all the person needs to do is add a `change` node and multiply that value by `1000` then feed it into the `moment` node.

**Comment by Just-another-pleb** [comment]
Any news on the update?

**Comment by hamsando** [comment]
Published .. (note that sometimes it can take some time for the NR palette manager to notice the update).

**Comment by hamsando** [comment]
The implementation adds a config option in the node. You select the format you want that 3rd output to be:
* HH:MM:SS (existing format, now considered default)
* seconds  
* minutes 
* hours 

As for whether or not it is worth keeping the HH:MM:SS - yup. The general goal is not to change the default behavior of the node. That was whenever anybody upgrades, everything should continue to work without any changes to flows needed.
