### ISSUE TITLE
countdown output

### ISSUE THREAD

**Issue by jarcher12** [hamsando/node-red-contrib-stoptimer-varidelay#2]
could you add a countdown output to the timer so it can be used in dashboard. as it is i have to use a different node to get the countdown. thanks

**Comment by hamsando** [comment]
Yup - actually the most recent commit here has that already. I'm having some difficulties publishing it to the npmjs/nodered site at the moment, but expect that to be resolved soon.

**Comment by hamsando** [comment]
Published successfully - should be in the NR pallette manager in the next few hours, once it propegates out.

**Comment by jarcher12** [comment]
Ok i like it only one slight problem i need the time in a numerical format not string. it is much more versatile, can put straight into a gauge for instance . I got the numbers out from the string but it would be cleaner just to have the raw numbers

**Comment by jarcher12** [comment]
this format does not easily convert to a number

**Comment by hamsando** [comment]
I'm open to making adjustment. I'm just not clear on the output you want. Are you looking for something like (for example) 
- msg.hh 
- msg.mm
- msg.ss
with the hh, mm, ss in int format filling those?

**Comment by jarcher12** [comment]
I was thinking just a payload of mm.ss as a float variable output from a fourth output. But it might be too much abs cofusing things rather than helping people.  I'm happy with it as it is.  The only node I could find that does what I need.  I have a countdown clock that can be set both from the ui dashboard and from telegram with a custom keyboard.  Thanks for the good work.

**Comment by hamsando** [comment]
I think it could be a little confusing. For the mm.ss, that isn't a normal representation of time. For example is 4 minutes 15 seconds 4.15 or 4.25 (as 15 seconds is 1/4 of a minute?)

**Comment by jarcher12** [comment]
yes i agree just me being lazy not wanting to mess with string conversions.  ; )

**Comment by hamsando** [comment]
Based on the above comments, I'm closing this off. The underlying function of the countdown output is there (as a string), having the output as a float/int representing HH MM SS isn't really practical.
