### ISSUE TITLE
Timer persist node-red restarts

### ISSUE THREAD

**Issue by Botched1** [hamsando/node-red-contrib-stoptimer-varidelay#3]
No idea how hard this would be to do - and none of the other stoptimer variants currently do this either - but it would be VERY nice if the timer would persist node-red reboot/restarts.

An example:
I use a 180 minute timer to turn off my pool chlorine pump after started. If I reboot/restart node-red during that period, my pump never turns off, as the timer is lost in the restart. I setup some time based alerts to work around this, but it would be even better if I didn't have to have extra nodes to catch this scenario.

So, that said, it would be awesome if the timer would pick up where it left off after a restart.

**Comment by hamsando** [comment]
I think I've got this about 90% done. Just running through some corner cases and code clean-up.

**Comment by hamsando** [comment]
Done! 0.4.1 is good to go. Let me know if you encounter any issues.

**Comment by Botched1** [comment]
@hamsando 
On my dev system the timer does not survive a node-red restart (but the timer does survive a flow reload). 

My dev system does not have persistent storage configured, though. Is that a requirement for this to work on a restart - the help doesn't say either way?

EDIT: Nope, I configured a persistent storage on it (as a secondary storage, not the default storage context), and it still does not survive a docker container restart / full node-red reload.
