### ISSUE TITLE
Timer does not survive node-red restart when running in a container due to location of stvd-timers directory

### ISSUE THREAD

**Issue by Botched1** [hamsando/node-red-contrib-stoptimer-varidelay#4]
When running node-red in a container, all data that needs to persist a reboot must be stored in the node-red user directory (the same one that the settings.js file is in).

Currently, 0.4.1 stores the stvd-timers directory in the main node-red code directory, and this does not persist container reboots. The dir needs to be put in the node-red user directory.

You probably need to check RED.settings.userDir in the code and use that as the root path for the folder.

Something remotely like:
const stvdtimersFolder = path.join(RED.settings.userDir, "stvd-timers")

**Comment by hamsando** [comment]
As you noted, this is a simple fix - I should be able to get it out later tonight.

**Comment by hamsando** [comment]
Should be resolved in 0.4.2 just released here, should be in the pallette soon I guess.

**Comment by Botched1** [comment]
Works perfectly! Thanks so much!
