### ISSUE TITLE
Node-RED 1.2 - continue timer after restart no longer working

### ISSUE THREAD

**Issue by Botched1** [hamsando/node-red-contrib-stoptimer-varidelay#6]
Might just be my system, but after upgrading Node-RED to v1.2 none of my timers restart/continue after a reboot anymore. This definitely used to work (almost positive it worked in 1.1.x), so I'm guessing that something in 1.2 made this stop working.

A file is getting created in stvd-timers, as expected, but the countdown does not continue after a node-red restart.

EDIT: I rolled the container back to 1.1.3 and the timer does re-start after nr reboot. So it does seem like a change in node-red 1.2.x broke something with this node...

**Comment by hamsando** [comment]
I can duplicate this - I'm investigating.

[Update]
Seems that my approach of calling emit on the input function to trigger the node with the data read from the file no longer works in1.2.2. I've changed my approach. Just running through some testing.

**Comment by hamsando** [comment]
Fixed in 0.4.5
