### ISSUE TITLE
2nd Output > Boolean

### ISSUE THREAD

**Issue by AndyZaa** [hamsando/node-red-contrib-stoptimer-varidelay#9]
I'm having an issue customizing the 2nd output. I'm using the Stoptimer with an Aqara motion sensor that sends out a boolean True when it detects motion. The sensor connects to the input of Stoptimer. I set the 2nd output to send a boolean False to turn off a light. The 1st output sends out a boolean True when the time expires as it should. No matter if I set the 2nd output to send a boolean T or F, it always sends a True when the time expires. The 2nd output works fine for strings or numbers which I can set to anything, and it is output.

Am I doing something wrong? I tried the other 3 Stoptimers which seems to share the code and they all do the same thing, so perhaps it is my error. Thank you for a great node, though!

![Stoptimer 1](https://user-images.githubusercontent.com/55149357/104828733-6b829700-583a-11eb-8724-3abedefef9f4.png)
![Stoptimer 2](https://user-images.githubusercontent.com/55149357/104828734-6b829700-583a-11eb-9eec-b87e68bc589a.png)

P.S. I know the 2nd output isn't tied to the light in my screenshot. I was just trying the different stoptimers connected to debugs to see if they would work.

**Comment by hamsando** [comment]
I don't think you are doing anything wrong, and it is easily replicated. I'll take a look.

**Comment by hamsando** [comment]
Fixed in 0.4.6 -- Just released (may take some time for your palette to notice the new update).

**Comment by AndyZaa** [comment]
Works perfectly now! Thank you for your work.
